Setup Deploy Key to bypass ruleset (#10)

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -44,21 +44,22 @@ jobs:
       - name: Install Dependencies
         run: npm install
 
-      # Step 6: Build the Application
+      # Step 5: Build the Application (this creates the dist/ folder)
       - name: Build
         run: npm run build
 
-      # Step 7: Bundle the `dist` folder
-      - name: Bundle dist folder
-        run: zip -r dist.zip dist
+      # Step 6: Verify dist folder
+      - name: Verify dist folder exists
+        run: |
+          if [ ! -d "dist" ]; then
+            echo "dist folder does not exist. Build failed."
+            exit 1
+          fi
 
-      - name: Set up SSH deploy key
-        uses: webfactory/ssh-agent@v0.5.4
-        with:
-          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
-
+      # Step 7: Commit version bump (if applicable) and push
       - name: Determine Next Version and Update package.json
         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+
         id: get_version
         run: |
           git config --global user.email "andy.barraford@gmail.com"
@@ -96,14 +97,14 @@ jobs:
         run: |
           git push origin main --force
 
-      # Step 9: Configure Git User
+      # Step 8: Configure Git User
       - name: Configure Git
         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
 
-      # Step 10: Create and Push Tag with Stash, Pull, and Reapply Changes
+      # Step 9: Create and Push Tag with Stash, Pull, and Reapply Changes
       - name: Create and Push Tag
         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
         run: |
@@ -118,7 +119,7 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      # Step 11: Create GitHub Release
+      # Step 10: Create GitHub Release
       - name: Create GitHub Release
         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
         id: create_release
@@ -132,7 +133,7 @@ jobs:
           draft: false
           prerelease: false
 
-      # Step 12: Upload Release Asset
+      # Step 11: Upload Release Asset
       - name: Upload Release Asset
         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
         uses: actions/upload-release-asset@v1
@@ -144,10 +145,11 @@ jobs:
           asset_name: dist.zip
           asset_content_type: application/zip
 
-      # Step 13: Clean Up
+      # Step 12: Clean Up
       - name: Clean Up
         run: rm dist.zip
 
+      # Step 13: Publish to npm
       - name: Publish to npm
         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
         run: |
